# Site settings
title: Wayne
email: vvayneshu@gmail.com
description: "Thoughts, projects, and stuff I'm learning about" 
baseurl: ""
url: "vvayne.github.io/about/"
twitter_username: none
github_username:  vvayne

# Build settings
markdown: kramdown
permalink: pretty