# Site settings
title: Hi I'm Wayne
email: vvvayne@outlook.com
description: "Thoughts, projects, and stuff I'm learning about" 
baseurl: ""
url: "vvayne.github.io"
twitter_username: none
github_username:  vvayne

# Build settings
markdown: kramdown
permalink: pretty
